name: todo_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  flutter_svg: ^1.1.5
  get_it: ^7.2.0
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  flutter_slidable: ^2.0.0
  google_fonts: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  freezed: ^2.0.3+1
  json_serializable: ^6.4.1
  dart_code_metrics: ^4.15.2


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

